# Generated by Django 6.0.6 on 2026-07-05 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="erosiondata",
            name="raw_delta_ha",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="erosiondata",
            name="water_area_ha",
            field=models.FloatField(default=0.0),
        ),
    ]
