# Copyright (c) 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys
import json
import datetime
from typing import Any, List
from dotenv import load_dotenv

from google.adk.agents import LlmAgent
from google.adk.agents.context import Context
from google.adk.apps import App
from google.adk.events.event import Event, EventActions
from google.adk.models import Gemini
from google.adk.workflow import START, Edge, Workflow, node
from google.genai import types
from pydantic import BaseModel, Field

# Load environment variables
load_dotenv()

# Force standard Gemini API usage rather than Vertex AI for local development
os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "False"
if "GEMINI_API_KEY" in os.environ and "GOOGLE_API_KEY" not in os.environ:
    os.environ["GOOGLE_API_KEY"] = os.environ["GEMINI_API_KEY"]

MODEL_NAME = "gemini-3.1-flash-lite"

# ==========================================
# Phase 1: Schemas and Agent Definitions
# ==========================================

class GISParams(BaseModel):
    """Pydantic model representing structured query parameters parsed by Agent A."""
    start_date: str = Field(description="The start date in YYYY-MM-DD format (available range: 2018-01-01 to 2026-12-31).")
    end_date: str = Field(description="The end date in YYYY-MM-DD format (available range: 2018-01-01 to 2026-12-31).")
    latitude_min: float = Field(description="Minimum latitude bounding box boundary (Majuli: ~26.80).")
    latitude_max: float = Field(description="Maximum latitude bounding box boundary (Majuli: ~27.15).")
    longitude_min: float = Field(description="Minimum longitude bounding box boundary (Majuli: ~93.90).")
    longitude_max: float = Field(description="Maximum longitude bounding box boundary (Majuli: ~94.60).")
    indices: List[str] = Field(description="Remote-sensing indices requested, e.g. ['NDVI', 'NDWI', 'Erosion', 'Slope'].")


class RiskReport(BaseModel):
    """Pydantic model representing the environmental analyst assessment generated by Agent B."""
    anomaly_detected: bool = Field(description="True if any abnormal erosion spikes or flood inundation peaks are identified.")
    severity: str = Field(description="Overall severity assessment: 'LOW', 'MEDIUM', 'HIGH', or 'CRITICAL'.")
    findings: List[str] = Field(description="Key findings and anomalies observed in the indices and data payload.")
    risk_report: str = Field(description="A comprehensive environmental risk report and interpretation of the geospatial metrics.")


class GeospatialWorkflowState(BaseModel):
    """Pydantic model representing the workspace/workflow state."""
    raw_query: str = ""
    sanitization_error: str | None = None
    validation_error: str | None = None
    gis_params: GISParams | None = None
    mcp_payload: str | None = None
    risk_report: RiskReport | None = None
    status: str = "started"
    notes: str = ""


# ==========================================
# Node 1: Security check (Sanitization)
# ==========================================

@node
def sanitize_input(ctx: Context, node_input: Any) -> Event:
    """Security Guardrail: Sanitizes and validates the user prompt before Agent A processing.
    Detects and rejects potential prompt injection attempts or malicious keywords.
    """
    raw_query = ""
    if isinstance(node_input, dict):
        raw_query = node_input.get("query", "")
    elif hasattr(node_input, "parts"):  # Content object
        raw_query = "".join(part.text for part in node_input.parts if part.text)
    else:
        raw_query = str(node_input)

    # Prompt injection keywords to look out for
    injection_keywords = [
        "ignore instructions",
        "ignore previous",
        "bypass",
        "override",
        "system prompt",
        "you must output",
        "ignore rules",
    ]
    
    query_lower = raw_query.lower()
    is_injection = any(kw in query_lower for kw in injection_keywords)

    if is_injection:
        error_msg = "SECURITY ALERT: Prompt injection attempt detected. Access denied."
        return Event(
            output=error_msg,
            content=types.Content(role="model", parts=[types.Part.from_text(text=error_msg)]),
            actions=EventActions(
                route="flagged",
                state_delta={
                    "raw_query": raw_query,
                    "sanitization_error": error_msg,
                    "status": "security_flagged",
                    "notes": error_msg
                }
            )
        )

    # Safe to proceed
    return Event(
        output=raw_query,
        actions=EventActions(
            route="clean",
            state_delta={
                "raw_query": raw_query,
                "status": "sanitized"
            }
        )
    )


@node
def security_failed_fallback(ctx: Context, node_input: Any) -> Event:
    """Fallback node when input sanitization fails."""
    err = ctx.state.get("sanitization_error") or "Security checks failed."
    return Event(
        output=err,
        actions=EventActions(
            state_delta={"status": "failed", "notes": err}
        )
    )


# ==========================================
# Agent A: GIS Operator
# ==========================================

gis_operator = LlmAgent(
    name="gis_operator",
    model=Gemini(
        model=MODEL_NAME,
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    instruction=(
        "You are a GIS Operator agent. Your task is to extract structured geospatial query parameters "
        "from the user's natural language request. You must output a JSON conforming to the GISParams schema. "
        "Default bounding box for Majuli Island if unspecified: min_lat=26.80, max_lat=27.15, min_lon=93.90, max_lon=94.60. "
        "Default date range if unspecified: start_date='2018-01-01', end_date='2025-12-31'."
    ),
    output_schema=GISParams,
    output_key="gis_params",
)


# ==========================================
# Node 3: Validation, Scope Capping & MCP Query
# ==========================================

@node
async def validate_bounds_and_fetch_data(ctx: Context, node_input: Any) -> Event:
    """Security Guardrail & Data Retrieval:
    1. Bounds-checks coordinates and dates to prevent malformed queries from reaching backend.
    2. Caps query scope (max 5 years temporal range) to avoid backend loop exhaustions.
    3. Spawns MCP server client to query stats and config.
    """
    gis_dict = ctx.state.get("gis_params")
    if not gis_dict:
        error_msg = "GIS Parameters extraction failed."
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )

    try:
        gis_params = GISParams.model_validate(gis_dict)
    except Exception as e:
        error_msg = f"Failed to validate GIS parameters: {str(e)}"
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )

    # 1. Date Range checks
    try:
        start_dt = datetime.datetime.strptime(gis_params.start_date.strip(), "%Y-%m-%d")
        end_dt = datetime.datetime.strptime(gis_params.end_date.strip(), "%Y-%m-%d")
    except ValueError:
        error_msg = "Invalid date format. Dates must be in YYYY-MM-DD format."
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )

    min_allowed = datetime.datetime(2018, 1, 1)
    max_allowed = datetime.datetime(2026, 12, 31)

    if not (min_allowed <= start_dt <= max_allowed) or not (min_allowed <= end_dt <= max_allowed):
        error_msg = "Requested dates are out of bounds. Data is only available between 2018-01-01 and 2026-12-31."
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )

    if start_dt > end_dt:
        error_msg = "Start date cannot be after the end date."
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )

    # CAPPING SCOPE: Cap queries to a max range of 5 years to protect backend resource exhaustion
    if (end_dt - start_dt).days > 5 * 365:
        clamped_end = start_dt + datetime.timedelta(days=5 * 365)
        gis_params.end_date = clamped_end.strftime("%Y-%m-%d")
        ctx.state["gis_params"]["end_date"] = gis_params.end_date  # Update state
        notes = f"Warning: Date range capped to 5 years ({gis_params.start_date} to {gis_params.end_date}). "
    else:
        notes = ""

    # 2. Coordinate Bounding Box checks (Majuli Island geographic bounds + safe margin)
    lat_min, lat_max = 26.70, 27.20
    lon_min, lon_max = 93.80, 94.70

    if not (lat_min <= gis_params.latitude_min <= lat_max) or not (lat_min <= gis_params.latitude_max <= lat_max):
        error_msg = f"Latitude coordinates out of Majuli bounds (must be between {lat_min} and {lat_max})."
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )

    if not (lon_min <= gis_params.longitude_min <= lon_max) or not (lon_min <= gis_params.longitude_max <= lon_max):
        error_msg = f"Longitude coordinates out of Majuli bounds (must be between {lon_min} and {lon_max})."
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )

    if gis_params.latitude_min > gis_params.latitude_max or gis_params.longitude_min > gis_params.longitude_max:
        error_msg = "Invalid coordinate bounds: minimum coordinate cannot exceed maximum coordinate."
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )

    # 3. Pull metrics from MCP server subprocess using stdio transport
    from mcp import ClientSession, StdioServerParameters
    from mcp.client.stdio import stdio_client

    python_exe = sys.executable or r"D:\agy2-projects\Geodrishti-geospatial-agent\.venv\Scripts\python.exe"
    mcp_script = os.path.join(os.path.dirname(__file__), "mcp_server.py")
    
    server_params = StdioServerParameters(
        command=python_exe,
        args=[mcp_script],
        env=os.environ.copy()
    )

    try:
        async with stdio_client(server_params) as (read, write):
            async with ClientSession(read, write) as session:
                await session.initialize()
                
                # Fetch regional configuration details from MCP server
                gis_config_res = await session.call_tool("get_gis_config", arguments={})
                gis_config = json.loads(gis_config_res.content[0].text)

                # Fetch erosion statistics from MCP server
                stats_res = await session.call_tool("get_erosion_stats", arguments={})
                stats_list = json.loads(stats_res.content[0].text)

                # Filter metrics by temporal bounds of query
                start_year = start_dt.year
                end_year = end_dt.year
                filtered_stats = [item for item in stats_list if start_year <= item.get("year", 0) <= end_year]

                payload = {
                    "gis_config": gis_config,
                    "historical_erosion_stats": filtered_stats,
                    "clamped_query_bounds": {
                        "start_date": gis_params.start_date,
                        "end_date": gis_params.end_date,
                        "latitude_min": gis_params.latitude_min,
                        "latitude_max": gis_params.latitude_max,
                        "longitude_min": gis_params.longitude_min,
                        "longitude_max": gis_params.longitude_max,
                        "indices": gis_params.indices
                    }
                }
                
                payload_str = json.dumps(payload)
                return Event(
                    output=payload_str,
                    actions=EventActions(
                        route="valid",
                        state_delta={
                            "mcp_payload": payload_str,
                            "status": "data_retrieved",
                            "notes": notes + "Geospatial metrics pulled successfully from backend via MCP tools."
                        }
                    )
                )
    except Exception as e:
        error_msg = f"MCP Server invocation failed: {str(e)}"
        return Event(
            output=error_msg,
            actions=EventActions(route="invalid", state_delta={"validation_error": error_msg, "status": "validation_failed"})
        )


@node
def validation_failed_fallback(ctx: Context, node_input: Any) -> Event:
    """Fallback node when bounding validation or MCP fetch fails."""
    err = ctx.state.get("validation_error") or "Validation check failed."
    return Event(
        output=err,
        actions=EventActions(
            state_delta={"status": "failed", "notes": err}
        )
    )


# ==========================================
# Agent B: Environmental Analyst
# ==========================================

environmental_analyst = LlmAgent(
    name="environmental_analyst",
    model=Gemini(
        model=MODEL_NAME,
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    instruction=(
        "You are an Environmental Analyst agent. Your task is to review the JSON data payload containing "
        "regional metrics and historical erosion stats, detect anomalies (like sudden erosion hikes), "
        "assess risk severity, outline findings, and produce a formal risk report conforming to the RiskReport schema."
    ),
    output_schema=RiskReport,
    output_key="risk_report",
)


# ==========================================
# Workflow definition (ADK Graph)
# ==========================================

geospatial_workflow = Workflow(
    name="geospatial_analyst_workflow",
    edges=[
        # Sanitization Gate
        Edge(from_node=START, to_node=sanitize_input),
        Edge(from_node=sanitize_input, to_node=security_failed_fallback, route="flagged"),
        Edge(from_node=sanitize_input, to_node=gis_operator, route="clean"),
        
        # Agent A Parsing & Validation Gate
        Edge(from_node=gis_operator, to_node=validate_bounds_and_fetch_data),
        Edge(from_node=validate_bounds_and_fetch_data, to_node=validation_failed_fallback, route="invalid"),
        Edge(from_node=validate_bounds_and_fetch_data, to_node=environmental_analyst, route="valid"),
    ],
    state_schema=GeospatialWorkflowState,
)

app = App(
    root_agent=geospatial_workflow,
    name="geodrishti_agent_app",
)
